function x_next = koopmanTruthStateFcn(x, u)
% x : 12x1 plant state
% u : 3x1 input
%Return next 12-states
persistent A B
if isempty(A) || isempty(B)
    S = load("koo_model.mat");   % must contain A and B
    A = S.A;
    B = S.B;
end

x_next = koopmanPlantStep(x, u, A, B);
end

function x_next = koopmanPlantStep(x,u,A,B)
% Discrete-time Koopman plant
%
% x : 12x1 physical state
% u : 3x1 control input
% A : 25x25 Koopman state matrix
% B : 25x3  input matrix
%
% Returns:
%   x_next : 12x1 next physical state

x = x(:);
u = u(:);

% Lift current physical state
z = koopmanPsi(x);      % 25x1


% Koopman step in lifted space
z_next = A*z + B*u;     % 25x1

% Recover 12-state physical state
x_next = z_next(1:12);

% Recompute derivative-like states
x_next(7:12) = x_next(1:6) - x(1:6);
end


function z = koopmanPsi(x)
% x is 12x1:
% [x y z alpha beta gamma dx dy dz dalpha dbeta dgamma]
%return 25x1 z matrix

x = x(:);

z = [ ...
    x(1) ...
    x(2) ...
    x(3) ...
    x(4) ...
    x(5) ...
    x(6) ...
    x(7) ...
    x(8) ...
    x(9) ...
    x(10) ...
    x(11) ...
    x(12) ...
    1 ...
    sqrt(x(1)^2 + x(2)^2) ...
    sqrt(x(1)^2 + x(3)^2) ...
    sqrt(x(2)^2 + x(3)^2) ...
    sin(x(4)) ...
    sin(x(5)) ...
    sin(x(6)) ...
    tan(x(4)) ...
    tan(x(5)) ...
    tan(x(6)) ...
    tanh(x(4)) ...
    tanh(x(5)) ...
    tanh(x(6)) ...
    ]';

end

